framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
    session: true
    # Vous pouvez ajouter d'autres configurations ici selon vos besoins

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
